force_drivers+=" \
 amlogic-gkitool \
 amlogic-debug-iotrace \
 amlogic-hwspinlock \
 amlogic-debug \
 amlogic-secmon \
 amlogic-cpuinfo \
 user_fault \
 amlogic-memory-debug \
 clk-scmi \
 amlogic-clk \
 amlogic-clk-soc-a9 \
 amlogic-gpio \
 amlogic-pinctrl-a4 \
 amlogic-mailbox \
 amlogic-pwm \
 gpio-regulator \
 amlogic-reset \
 amlogic-power \
 amlogic-cpufreq \
 amlogic-thermal \
 amlogic-mmc \
 amlogic-efuse-unifykey \
 amlogic-i2c \
 amlogic-spi \
 amlogic-rng \
 tee \
 amlogic-tee \
 optee \
 aml_smmu \
 dvb-core \
 amlogic-pm \
 amlogic-adc \
 amlogic-input \
 amlogic-watchdog \
 amlogic-dvb \
 aml_media \
 amlogic-usb \
 amlogic-irblaster \
 amlogic-phy-debug \
 amlogic-inphy \
 aml_drm \
 amlogic-soc-amfc \
 amlogic-soc-erofs \
 system_heap \
"
